#!/sbin/busybox sh
cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

SECONDROM=1
NOBOOTLOGO=0
mkdir -p /dev/block
mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/urandom c 1 9
mkdir /dev/input
mkdir /dev/graphics
mknod /dev/graphics/fb0 c 29 0
mknod /dev/input/event0 c 13 64
mknod /dev/input/event1 c 13 65
mknod /dev/input/event2 c 13 66
mknod /dev/input/event8 c 13 72
mknod /dev/input/event9 c 13 73
mknod /dev/ashmem c 10 34
mknod /dev/block/mmcblk0p12 b 179 12
mknod /dev/block/mmcblk0p13 b 179 13
mknod /dev/block/mmcblk0p14 b 179 14
mknod /dev/block/mmcblk0p15 b 179 15
mknod /dev/block/loop0 b 7 0

mkdir /mnt
chmod 755 /mnt
mkdir /.secondrom
mount /dev/block/mmcblk0p15 /.secondrom

NEXTBOOT=`cat /.secondrom/.nextboot`
rm -f /.secondrom/.nextboot
DEFAULTROM=`cat /.secondrom/.defaultrom`

if grep -q warmboot=0x77665502 /proc/cmdline ; then
  NEXTBOOT=0
fi

if [ "$NEXTBOOT" != "0" ];then
  echo 200 > /sys/class/timed_output/vibrator/enable
  echo 255 > /sys/class/leds/led_7-rgb1-red/brightness
  echo   0 > /sys/class/leds/led_8-rgb2-green/brightness
  echo 255 > /sys/class/leds/led_9-rgb3-blue/brightness
  cat /dev/input/event0 > /dev/keycheck &
  sleep 3
  echo 0 > /sys/class/leds/led_7-rgb1-red/brightness
  echo 0 > /sys/class/leds/led_8-rgb2-green/brightness
  echo 0 > /sys/class/leds/led_9-rgb3-blue/brightness
  [ -s /dev/keycheck ] && NEXTBOOT=0
  mount /dev/block/mmcblk0p13 /cache
  [ -e /cache/recovery/boot ] && NEXTBOOT=0
  rm -f /cache/recovery/boot
  umount /cache
fi

if [ "$NEXTBOOT" == "0" ]; then
  mv -f /res/etc /
  umount /.secondrom
  echo 0 > /proc/sys/kernel/rom_feature_set
  mv -f /res/misc/init.40/* /
  mv -f /res/misc/recovery/* /
  chmod 755 /innt
  chmod 755 /*.sh
  chmod 644 /*.rc
  chmod 644 /*.fstab
  chmod -R 755 /lib
  exec /sbin/init2
fi

SECONDROM=1
NOBOOTLOGO=1
[ -f /.secondrom/.secondrom/system.img ] || SECONDROM=0
[ -f /.secondrom/.nobootlogo ] && NOBOOTLOGO=1

if [ "$SECONDROM" == "0" ];then
  if [ "$NOBOOTLOGO" == "0" ];then
    /sbin/choose_rom $SECONDROM
  fi
else
  if [ "$NEXTBOOT" == "1" ];then
    SECONDROM=0;
  elif [ "$NEXTBOOT" == "2" ];then
    SECONDROM=1;
  else
    if [ "$NOBOOTLOGO" == "1" ];then
      SECONDROM=$DEFAULTROM
    elif [ "$DEFAULTROM" == "1" ];then
      /sbin/choose_rom $SECONDROM
      if [ "$?" == "1" ]; then
        SECONDROM=0
      else
        SECONDROM=1
      fi
    else
      /sbin/choose_rom $SECONDROM
      if [ "$?" == "1" ]; then
        SECONDROM=1
      else
        SECONDROM=0
      fi
    fi
  fi
fi

if [ "$SECONDROM" == "1" ]; then
  mount -t ext4 /.secondrom/media/.secondrom/system.img /system
else
  mount -t ext4 /dev/block/mmcblk0p12 /system
fi


AOSP=0
MIUI=0
CM10=0
JB=0

[ -f /system/framework/miui-framework.jar ] && MIUI=1
[ -f /system/lib/ssl/engines/libkeystore.so ] && JB=1
[ -f /system/framework/seccamera.jar ] || CM10=1

if [ "$JB" == 1 ];
then
  if [ "$CM10" == 1 ];
  then
    echo 3 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.cm10/* /
    rm /lib/modules/wlan.ko
  else
    echo 2 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.41/* /
  fi
else
  if [ "$AOSP" == "1" ];
  then
    echo 1 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.cm9/* /
    rm /lib/modules/wlan.ko
  else
    echo 0 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.40/* /
  fi;
fi

#if [ "$SECONDROM" == "1" ];then
#  mv /init.smdk4x12.rc.2 /init.smdk4x12.rc
#  mv /init.rc.2 /init.rc
#  mv /fstab.smdk4x12.2 /fstab.smdk4x12
#else
#  rm -f /init.rc.2 /init.smdk4x12.rc.2 /fstab.smdk4x12.2
#fi

umount -f /system
umount -f /.secondrom
	
rm -rf /res/misc/init*
chmod 755 /innt
chmod 755 /*.sh
chmod 644 /*.rc
chmod 644 /*.fstab
chmod -R 755 /lib

# cpu undervolting interfaces
insmod /lib/modules/cpu_undervolting.ko
# additional CPU governors
insmod /lib/modules/cpufreq_hotplug.ko
insmod /lib/modules/cpufreq_lulzactiveq.ko
# additional I/O schedulers
insmod /lib/modules/sio-iosched.ko
insmod /lib/modules/vr-iosched.ko

exec /sbin/init2

